core/urls.py
from django.urls import path
from .views import MainView, CartView

app_name = 'core'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('cart/', CartView.as_view(), name='basket'),
]

menu/urls.py
from django.urls import path
from .views import DishUpdateView, basket_adding, remove_from_basket

app_name = 'menu'

urlpatterns = [
    path('add-to-basket/', basket_adding, name="add_to_basket"),
    path('remove-from-basket/', remove_from_basket, name="remove_from_basket"),
    path('<int:pk>/update/', DishUpdateView.as_view(), name='menu_detail'),
]

restaurant/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('menu/', include('menu.urls', namespace='menu')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    
urlpatterns += [url(r'^i18n/', include('django.conf.urls.i18n'))]

core/models.py
from django.db import models

# Create your models here.

menu/models.py
from decimal import Decimal
from django.urls import reverse
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from django.template.loader import render_to_string
import requests


class Dish(models.Model):
    title = models.CharField(verbose_name="Название блюда", max_length=100, null=True, default=None)
    image = models.ImageField(verbose_name="Картинка", upload_to="menu", null=True, default="")
    price = models.DecimalField(verbose_name="Цена", max_digits=10, decimal_places=2, default=0)
    created_date = models.DateTimeField(default=timezone.now)
    recipe = models.TextField(verbose_name="Краткий рецепт", )


    def __str__(self):
        return '%s' % self.id

    def get_absolute_url(self):
        return reverse("menu:menu_detail", kwargs={"pk": self.pk})


class BasketItem(models.Model):
    dish = models.ForeignKey(to='Dish', null=True, on_delete=models.CASCADE, unique=False)
    amount = models.PositiveIntegerField(default=1)
    add_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s' % self.dish


class Basket(models.Model):
    total = models.DecimalField(verbose_name='total', max_digits=10, decimal_places=2, default=0)
    session_key = models.CharField(max_length=128, default=None)
    dishes = models.ManyToManyField(to='BasketItem')

    def count_total_price(self):
        items = self.dishes.all()
        total = 0
        for item in items:
            total += item.dish.price * item.amount
        self.total = Decimal(total)
        self.save()

    def __str__(self):
        return '%s' % self.id


class Order(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200, null=True, default=None)
    phone_number = PhoneNumberField(verbose_name='Мобильный телефон', default=None)
    delivery_date = models.DateTimeField(verbose_name="Время (дата) доставки", default=timezone.now)
    location = models.CharField(verbose_name="Адрес Доставки (киоск)", max_length=225, null=True, default=None)
    date_ordered = models.DateTimeField(auto_now=True)
    basket = models.OneToOneField('Basket', on_delete=models.CASCADE, related_name='basket', default=None)
    sent_by_bot = models.BooleanField(default=False)


    def send_order_by_bot(self):
        context = {
            "order_id": self.id,
            "name": self.name,
            "phone_number": self.phone_number,
            "delivery_date": self.delivery_date,
            "location": self.location,
            "date_ordered": self.date_ordered,
            "items": self.basket.dishes.all(),
        }
        message = render_to_string('messages/message.txt', context)
        bot_token = '782909773:AAEnUd0rbfXEGQEc8hD3QFsBVdOSHH62ehA'
        bot_chatID = '551207729'
        send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=' + message

        response = requests.get(send_text)

        return response.json()

core/forms.py
from django import forms


class OrderForm(forms.Form):
    phone_number = forms.RegexField(regex=r'^\+?1?\d{9,15}$', 
                                error_message = ("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")) 
    location = forms.CharField()
    comment = forms.CharField()
    item 
    date_create 
    delivery

menu/forms.py
from django import forms
from .models import Dish


class DishForm(forms.ModelForm):
   
    class Meta:
        model = Dish
        fields = ['title', 'recipe', ]

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView
from menu.models import Dish, Basket, Order


class MainView(CreateView):
    template_name = 'core/main.html'
    model = Dish
    fields = ['title', 'image', 'price', 'recipe']
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['items'] = Dish.objects.all().order_by('-created_date')
        return context


class CartView(CreateView):
    template_name = 'core/cart.html'
    model = Order
    fields = ['name', 'phone_number', 'location', 'delivery_date']
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Basket.objects.filter(session_key=self.request.session.session_key)
        return context

    def form_valid(self, form):
        basket = Basket.objects.get(session_key=self.request.session.session_key)
        self.object = form.save(commit=False)
        self.object.basket = basket
        self.object.save()
        self.object.send_order_by_bot()
        self.request.session.flush()
        
        return super().form_valid(form)

menu/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import UpdateView
from .models import Dish, Basket, BasketItem
from .forms import DishForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string


class DishUpdateView(UpdateView):
    model = Dish
    fields = ['title', 'image', 'price', 'recipe']
    template_name = 'menu/detail_update_dish.html'

    def get_object(self):
        id = self.kwargs.get("pk")
        return get_object_or_404(Dish, id=id)


def basket_adding(request):
    return_dict = dict()
    session_key = request.session.session_key
    data = request.POST
    print(data.get("dish_id"))
    dish = Dish.objects.filter(id=data.get("dish_id")).first()
    amount = data.get("dish_amount")
    new_basket, created = Basket.objects.get_or_create(session_key=session_key)
    basket_item, created = BasketItem.objects.get_or_create(dish=dish,
                                                            defaults={"amount": amount}
                                                            )
    if not created:
        basket_item.amount += int(amount)
        basket_item.save(force_update=True)

    new_basket.dishes.add(basket_item)
    new_basket.count_total_price()
    dish_total = new_basket.dishes.count()
    return_dict["dish_total"] = dish_total
    return JsonResponse(return_dict)


def remove_from_basket(request):
    return_dict = dict()
    session_key = request.session.session_key
    data = request.POST
    dishes_id = data.get("remove_item_id")
    if dishes_id:
        basket = Basket.objects.get(session_key=session_key)
        basket.dishes.get(id=dishes_id).delete()
        return_dict["is_deleted"] = True
        return_dict['dishes_total'] = basket.dishes.count()
        if basket.dishes.count() < 1 or basket.total <= 3.50:
            basket.delete()
            return_dict['empty_basket'] = render_to_string('core/empty_basket.html')
        else:
            basket.count_total_price()
        return_dict['basket_total'] = basket.total
    return JsonResponse(return_dict)

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
<style>
    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
        background-color: #f4f4f4;
        height: 100%;
        width: 100%;
        margin-top: 70px;
    }
    .main-wrapper {
        max-width: 1200px;
        margin: 0 auto;
        background-color: #fff;
        min-height: 700px;
    }
</style>

{% block header %}
    {% include 'core/header.html' %}
{% endblock %}

<div class="main-wrapper">
{% block content %}
{% endblock %}
</div>
{% block footer %}
{% endblock %}

</body>
</html>

core/templates/core/cart.html
{% extends 'core/base.html' %}
{% block content %}
    <style>
        .page-title {
            text-align: center
        }
        .cart-container {
            padding: 25px;
        }
        .cart-item {
            display: flex;
            flex-direction: row;
            padding: 20px 0;
        }
        .item {
            flex: 1 55%;
        }
        .item div {
            padding: 8px 0;
        }
        .item-amount {
            flex: 1 15%;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .item-total-price {
            flex: 1 15%;
            text-align: center;
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .form-item-delete {
            flex: 1 15%;
            text-align: center;    
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .cart-total {
            text-align: right;
            font-weight: 900;
            border-bottom: 3px solid red;
        }
        form {
            display: flex;
            flex-direction: column;
            margin: 0 auto;
            width: 50%;
        }
        img {
            max-width: 40%;
        }
        @media (max-width: 880px) {
            .table-info {
                display: none;
            }
            .hr {
                display: none;
            }
        }
        @media (min-width: 880px) {
            .table-info {
                display: flex;
                flex-direction: row;
            }
            .name-info {
                flex: 1 51%;
                padding-left: 30px;
            }
            .amount-info {
                flex: 1 10%;
            }
            .price-info {
                flex: 1 20%;
            }
            .empty-info {
                flex: 1 0%;    
            }
            .hr {
                display: block;
            }
        }
        @media (max-width: 700px) {
            .cart-item {
                flex-direction: column;
                text-align: center;
            }
        }
        input[type=text] {
            width: 100%;
            margin-bottom: 20px;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        input[type=tel] {
            width: 100%;
            margin-bottom: 20px;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }
        label {
            margin-bottom: 10px;
            display: block;
        }
        .button {
            text-align: center;
            text-transform: uppercase;
            cursor: pointer;
            font-size: 15px;
            letter-spacing: 4px;
            position: relative;
            background-color: red;
            border: none;
            color: #fff;
            padding: 8px;
            width: 200px;
            text-align: center;
            transition-duration: 0.4s;
            overflow: hidden;
            box-shadow: 0 5px 15px #193047;
            border-radius: 4px;
            margin: 0 auto;
        }
        .button:hover {
            background: #fff;
            box-shadow: 0px 2px 10px 5px #1abc9c;
            color: #000;
        }

        .button:after {
            content: "";
            background: #1abc9c;
            display: block;
            position: absolute;
            padding-top: 300%;
            padding-left: 350%;
            margin-left: -20px !important;
            margin-top: -120%;
            opacity: 0;
            transition: all 0.8s
        }

        .button:active:after {
            padding: 0;
            margin: 0;
            opacity: 1;
            transition: 0s
        }

        .button:focus { outline:0; }
        .pb-100 {
            padding-bottom: 100px;
        }
        .empty-basket {
            display: none;
        }
    </style>
    <div class="basket-wrapper">
        {% if object_list %}
        <h1 class="page-title">Оформить заказ</h1>
        <div class="table-info">
                <div class="name-info">Название (краткое описание)</div>    
                <div class="amount-info">Количество</div>
                <div class="price-info">Стоимость</div>
                <div class="empty-info"></div>
        </div>
        <hr class="hr">        
        {% for items in object_list %}
            <div class="cart-container">
                {% for item in items.dishes.all %}
                    <div class="cart-item">
                        <div class="item">
                            <div class="item-name">{{ item.dish.title }}</div>
                            <img src="{{ item.dish.image.url }}">
                            <div class="item-price">{{ item.dish.price }} рублей</div>
                            <div class="item-recipe">{{ item.dish.recipe }}</div>
                        </div>
                        <div class="item-amount">{{ item.amount }}</div>
                        <div class="item-total-price"></div>
                        <form class="form-item-delete" action="{% url 'menu:remove_from_basket' %}">
                            {% csrf_token %}
                            <a data-dish-id="{{ item.id }}" href="#" class="item-delete">удалить</a>
                        </form>
                    </div>
                {% endfor %}
                <div class="cart-total">Сумма заказа: {{ items.total }} рублей</div>
            </div>
        {% endfor %}  
            <div>
                <form class="pb-100" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="button" type="submit" value="Заказать"/>
                </form>
            </div>
        {% else %}
        <h1 class="page-title">Ваша корзина пуста</h1>
        {% endif %}
    </div>
    <div class="empty-basket"></div>
    <script>
        function itemTotalPrice () {
            var item_total_price = 0;    
            $('.cart-item').each(function (){
                var price = parseFloat($(this).find('.item-price').text());
                var amount = parseFloat($(this).find('.item-amount').text());
                item_total_price = price * amount;
                $(this).find('.item-total-price').text(item_total_price + ' рублей')
            })
        }
        itemTotalPrice()
        $('.item-delete').on('click', function (e) {
            e.preventDefault();
            var $this = $(this)
            var data = {};
            var csrf_token = $('.form-item-delete [name="csrfmiddlewaretoken"]').val();
            var url = $('.form-item-delete').attr('action');
            var remove_item_id = $(this).data('dishId');
            data.remove_item_id = remove_item_id;
            data['csrfmiddlewaretoken'] = csrf_token;
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function (data) {
                    if (data.dishes_total == 0) {
                        $('.basket-wrapper').hide();
                        $('.empty-basket').append(data.empty_basket).show();
                        $('.basket_count').html(0)
                    }
                    else if(data.is_deleted) {
                        $this.closest('.cart-item').remove();
                        $('.cart-total').text('Сумма заказа: ' + data.basket_total + ' рублей')
                        $('.basket_count').text(data.dishes_total)
                    }
                
                }
            })
        })
    </script>   
{% endblock %}

core/templates/core/empty_basket.html
<h1 class="page-title">Ваша корзина пуста</h1>

core/templates/core/header.html
<header>
    <!-- <style>
        header {
            height: 27px;
        }
        
    </style> -->
    <style>
        header.visible {
            transform: translateZ(0);
            box-shadow: 0 5px 17px 0 rgba(0, 0, 0, .05);
        }
    
        header {
            position: fixed;
            top: 0;
            height: 35px;
            width: 100%;
            background: #FFF;
            z-index: 3000;
        }
    
        .topnav {
            overflow: hidden;
            background-color: #333;
            display: flex;
            flex-direction: row;
            justify-content: space-evenly;
            align-items: center;
        }
    
        .topnav a {
            float: left;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }
    
        .topnav a:hover {
            color: #eb1c23;
        }
    
        .topnav .icon {
            display: none;
        }
    
        @media screen and (max-width: 600px) {
            .topnav a:not(:first-child) {
                display: none;
            }
    
            .topnav a.icon {
                float: right;
                display: block;
            }
        }
    
        @media screen and (max-width: 600px) {
            .topnav {
                display: block;
            }
    
            .topnav.responsive {
                position: relative;
            }
    
            .topnav.responsive .icon {
                position: absolute;
                right: 0;
                top: 0;
            }
    
            .topnav.responsive a {
                float: none;
                display: block;
                text-align: left;
            }
        }
        .container {
            display: inline-block;
            cursor: pointer;
        }
    
        .bar1, .bar2, .bar3 {
            width: 35px;
            height: 5px;
            background-color: #fff;
            margin: 6px 0;
            transition: 0.4s;
        }
    
        .change .bar1 {
            -webkit-transform: rotate(-45deg) translate(-9px, 6px);
            transform: rotate(-45deg) translate(-9px, 6px);
        }
    
        .change .bar2 {
            opacity: 0;
        }
    
        .change .bar3 {
            -webkit-transform: rotate(45deg) translate(-8px, -8px);
            transform: rotate(45deg) translate(-8px, -8px);
        }
        .basket_count {
            margin-left: 10px;
            border-radius: 22em;
            border: 4px solid red;
            padding: 5px 10px;
        }
    </style>
    <header class="visible">
        <div class="topnav" id="myTopnav">
            <a href="{% url 'core:main' %}" class="active">Главная</a>
            <a href="{% url 'core:basket' %}">Корзина<span class="basket_count">{{ dishes_count }}</span></a>
            <a href="javascript:void(0);" class="icon container" onclick="myFunction()">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </a>
        </div>
    </header>
    <script>
        function myFunction() {
            var x = document.getElementById("myTopnav");
            if (x.className === "topnav") {
                x.className += " responsive";
                x.classList.toggle("change");
            } else {
                x.className = "topnav";
            }
        }
    </script>
</header>

core/templates/core/main.html
{% extends 'core/base.html' %}
{% block content %}
    <style>
        .list-item {
            display: flex;
            flex-flow: row wrap;
            padding: 0 30px;
        }

        .item-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            flex: 1 33.3333333%;
            text-align: center;
            justify-content: space-between;
        }
        img {
            max-width: 80%;
        }
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .quantity {
            position: relative;
        }

        input[type=number]::-webkit-inner-spin-button,
        input[type=number]::-webkit-outer-spin-button
        {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type=number]
        {
            -moz-appearance: textfield;
        }

        .quantity input {
            width: 45px;
            height: 42px;
            line-height: 1.65;
            float: left;
            display: block;
            padding: 0;
            margin: 0;
            padding-left: 20px;
            border: 1px solid #eee;
        }

        .quantity input:focus {
            outline: 0;
        }

        .quantity-nav {
            float: left;
            position: relative;
            height: 42px;
        }

        .quantity-button {
            position: relative;
            cursor: pointer;
            border-left: 1px solid #eee;
            width: 20px;
            text-align: center;
            color: #333;
            font-size: 13px;
            font-family: "Trebuchet MS", Helvetica, sans-serif !important;
            line-height: 1.7;
            -webkit-transform: translateX(-100%);
            transform: translateX(-100%);
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            -o-user-select: none;
            user-select: none;
        }

        .quantity-button.quantity-up {
            position: absolute;
            height: 50%;
            top: 0;
            border-bottom: 1px solid #eee;
        }

        .quantity-button.quantity-down {
            position: absolute;
            bottom: -1px;
            height: 50%;
        }
        .add_to_cart {
            width: 100%;
        }
        #submit_btn {
            width: 50%;
            margin: 10px auto 0;
        }
        .item-recipe {
            font-size: 12px;
            text-align: start;
        }
        .item-add-form label {
            padding: 10px
        }
        .add-item-button {
            margin: 10px;    
        }
        h1 {
            text-align: center;
        }
        .button {
            text-align: center;
            text-transform: uppercase;
            cursor: pointer;
            font-size: 15px;
            letter-spacing: 4px;
            position: relative;
            background-color: red;
            border: none;
            color: #fff;
            padding: 8px;
            width: 200px;
            text-align: center;
            transition-duration: 0.4s;
            overflow: hidden;
            box-shadow: 0 5px 15px #193047;
            border-radius: 4px;
        }

        .button:hover {
            background: #fff;
            box-shadow: 0px 2px 10px 5px #1abc9c;
            color: #000;
        }

        .button:after {
            content: "";
            background: #1abc9c;
            display: block;
            position: absolute;
            padding-top: 300%;
            padding-left: 350%;
            margin-left: -20px !important;
            margin-top: -120%;
            opacity: 0;
            transition: all 0.8s
        }

        .button:active:after {
            padding: 0;
            margin: 0;
            opacity: 1;
            transition: 0s
        }

        .button:focus { outline:0; }
    </style>
    <div>
        <h1>Меню</h1>
        <div class="list-item">
            {% for menu in items %}
                <div class="item-container">
                    <div class="item">
                        {% if user.is_authenticated %}
                        <a href="{% url 'menu:menu_detail' menu.pk %}"><h2>{{ menu.title }}</h2></a>
                        {% else %}
                        <h2>{{ menu.title }}</h2>
                        {% endif %}
                        <img src="{{ menu.image.url }}"/>
                        <p class="item-recipe">{{ menu.recipe }}</p>
                    </div>
                    <form method="post" data-product-id="{{ menu.id }}" id="add-to-cart" class="add_to_cart"
                          action="{% url 'menu:add_to_basket' %}">
                        {% csrf_token %}
                        <div class="quantity">
                            <input type="number" value="1" min="1" id="amount"/>
                        </div>
                        <input class="button" id="submit_btn" type="submit" value="Заказать"/>
                </form>
                </div>
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <hr>
        <div class="item-add">
            <form action="." method="post" class="item-add-form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input class="button add-item-button" type="submit" value="Добавить" />
            </form>
        </div>
        {% endif %}
    </div>
    <script>
        $('.add_to_cart').on('submit', function (e) {
            e.preventDefault();
            var data = {};
            var csrf_token = $('#add-to-cart [name="csrfmiddlewaretoken"]').val();
            console.log(csrf_token)
            var url = $(this).attr('action');
            var dish_id = $(this).data('productId');
            console.log(dish_id)
            var dish_amount = $(this).find("#amount").val();
            console.log(dish_amount)
            data.dish_id = dish_id;
            data.dish_amount = dish_amount;
            data['csrfmiddlewaretoken'] = csrf_token;
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function (data) {
                    if (data.dish_total || data.dish_total === 0) {
                        $('.basket_count').text(data.dish_total)
                    }
                }
            })
        })

        jQuery('<div class="quantity-nav"><div class="quantity-button quantity-up">+</div><div class="quantity-button quantity-down">-</div></div>').insertAfter('.quantity input');
        jQuery('.quantity').each(function() {
        var spinner = jQuery(this),
            input = spinner.find('input[type="number"]'),
            btnUp = spinner.find('.quantity-up'),
            btnDown = spinner.find('.quantity-down'),
            min = input.attr('min'),
            max = input.attr('max');

        btnUp.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue >= max) {
            var newVal = oldValue;
            } else {
            var newVal = oldValue + 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
        });

        btnDown.click(function() {
            var oldValue = parseFloat(input.val());
            if (oldValue <= min) {
            var newVal = oldValue;
            } else {
            var newVal = oldValue - 1;
            }
            spinner.find("input").val(newVal);
            spinner.find("input").trigger("change");
        });
        });
    </script>
{% endblock %}

menu/templates/menu/detail_update_dish.html
{% extends 'core/base.html' %}
{% block content %}
    <style>
        form {
            display: flex;
            flex-direction: column;
            width: 50%;
            margin: 0 auto;
        }
        .update-item {
            width: 50%;
            margin: 0 auto;
        }
        .update-item-button {
            margin: 10px 0;
            background-color: red;
            color: #fff;
            border-radius: 2em;
            border: 2px solid #fff;
            padding: 10px;
        }
    </style>
    <div class="update-item">
            <h1>{{ object.title }}</h1>
            <img src="{{ object.image.url }}"/>
            <h3>Цена:</h3>
            <p>{{ object.price }}</p>
            <h3>Рецепт:</h3>
            <p>{{ object.recipe }}</p>
    </div>
    <div class="update-block">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input class="update-item-button" type="submit" value="Редактировать"/>
        </form>
    </div>
{% endblock %}